### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Astro-Otter-Space** [HamHamFonFon/deep-space-objects#39]
https://www.astrobin.com/r4p1in/?utm_source=facebook&utm_medium=post&utm_campaign=iotd
Done

**Comment by HamHamFonFon** [comment]
StDr98 - The opal nebula https://www.astrobin.com/w7kthv/?utm_source=facebook&utm_medium=post&utm_campaign=iotd&fbclid=IwAR2S0B33lVHQqcmlaGK2drWhqdt5c8IeCgqL5CgqJmQu2F3BpRtcLWxaVDQ

**Comment by Astro-Otter-Space** [comment]
LBN325

**Comment by HamHamFonFon** [comment]
NGC 539 (Arp 84) https://www.astrobin.com/06i285/B/
Menzel 2 : https://www.facebook.com/groups/AstronomyNo1/permalink/3539274442784279/

**Comment by Astro-Otter-Space** [comment]
Add sh2-173 https://www.facebook.com/117315445086929/posts/2051134668371654/?substory_index=0
DONE IN #45

**Comment by Astro-Otter-Space** [comment]
NGC4826
Sh2-71

DONE
